name: Java CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 레포지토리 체크아웃
      uses: actions/checkout@v4

    - name: JDK 21 설치
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: gradlew 권한 부여
      run: chmod +x gradlew

    - name: Docker Compose 설치
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: mysql 실행
      run: docker-compose up -d

    - name: 5초간 대기
      run: sleep 5

    - name: gradle 빌드
      run: ./gradlew build

    - name: 컨테이너 종료
      if: always()
      run: docker-compose down
